// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF39m1haij-Z4rFzD9p2jDshadNVP8_CM',
    appId: '1:353551246657:web:87eb628487d57f1b8dedc0',
    messagingSenderId: '353551246657',
    projectId: 'hexatour-e1459',
    authDomain: 'hexatour-e1459.firebaseapp.com',
    storageBucket: 'hexatour-e1459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFXMpO93EBv78V7P-UMMDeamJr9RGoRjs',
    appId: '1:353551246657:android:dc9c035b9a5ffcf58dedc0',
    messagingSenderId: '353551246657',
    projectId: 'hexatour-e1459',
    storageBucket: 'hexatour-e1459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbHtobON_B-tbOWjRaWjwkB_yPp2t5_w',
    appId: '1:353551246657:ios:7827f69076693ace8dedc0',
    messagingSenderId: '353551246657',
    projectId: 'hexatour-e1459',
    storageBucket: 'hexatour-e1459.appspot.com',
    androidClientId: '353551246657-am650g8mavm1ep40j6aa5ldi8quurro1.apps.googleusercontent.com',
    iosClientId: '353551246657-jrhfc3er4cvdnrjfvjjoulmdepf3v0u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hexatour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTbHtobON_B-tbOWjRaWjwkB_yPp2t5_w',
    appId: '1:353551246657:ios:7827f69076693ace8dedc0',
    messagingSenderId: '353551246657',
    projectId: 'hexatour-e1459',
    storageBucket: 'hexatour-e1459.appspot.com',
    androidClientId: '353551246657-am650g8mavm1ep40j6aa5ldi8quurro1.apps.googleusercontent.com',
    iosClientId: '353551246657-jrhfc3er4cvdnrjfvjjoulmdepf3v0u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hexatour',
  );
}
